# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
import zipfile
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer


# 1. Load CSV from ZIP
zip_path = "your-zip-path"
csv_filename = "your-csv-path"

with zipfile.ZipFile(zip_path,'r') as zip_ref:
  with zip_ref.open(csv_filename) as file:
    df = pd.read_csv(file, on_bad_lines='skip')

# 2. Preprocess the dataset
df = df[['title', 'authors', 'description']].dropna()

# 3. User mood input
user_mood = input("Enter your mood: ")

# 4. Load SentenceTransformer model
model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

# 5. Encode book descriptions
print("Encoding book descriptions (it can take a minute)...")
book_embeddings = model.encode(df['description'].tolist(), show_progress_bar=True)

# 6. Encode user mood
print("Encoding user mood...")
mood_embedding=model.encode([user_mood])

# 7. Compute cosine similarity
similarities = cosine_similarity(mood_embedding, book_embeddings)[0]
df['similarity'] = similarities

# 8. Remove duplicates by title
df = df.drop_duplicates(subset='title')

# 9. Recommend top books
recommended_books = df.sort_values(by='similarity', ascending=False).head(5)

# 10. Show results
print("\n📚 Top 5 book recommendations for your mood:\n")
for idx, row in recommended_books.iterrows():
  print(f"{row['title']} by {row['authors']}")
  print(f"{row['description'][:500]}...")  # First 500 character
  print("—" * 50)